# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Ian Monroe <imonroe@kde.org>


include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/clang-format.yml
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/linux-qt6-next.yml
      - /gitlab-templates/windows-qt6.yml

suse_tumbleweed_qt611:
  before_script:
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1
    - git clone https://invent.kde.org/sysadmin/repo-metadata.git ci-utilities/repo-metadata/ --depth=1
    - git clone https://github.com/mborgerding/kissfft.git --depth=1 --branch 131.2.0 kissfft-src

suse_tumbleweed_qt612:
  before_script:
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1
    - git clone https://invent.kde.org/sysadmin/repo-metadata.git ci-utilities/repo-metadata/ --depth=1
    - git clone https://github.com/mborgerding/kissfft.git --depth=1 --branch 131.2.0 kissfft-src

windows_qt611:
  before_script:
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1
    - git clone https://invent.kde.org/sysadmin/repo-metadata.git ci-utilities/repo-metadata/ --depth=1
    - git clone https://github.com/mborgerding/kissfft.git --depth=1 --branch 131.2.0 kissfft-src
    - git clone https://github.com/libsdl-org/SDL.git --depth=1 --branch release-3.4.12 sdl3-src
